name: Crypto Alert

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:        # manual trigger

jobs:
  check-crypto:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      EXTRA_CHAT_ID: ${{ secrets.EXTRA_CHAT_ID }}
      TWELVE_API_KEY: ${{ secrets.TWELVE_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas matplotlib

      - name: Run Crypto Alert script
        run: python crypto_alert.py
